<font size="5"><b>Case Study I</b><br><br>
Module 12: Reinforcement Learning
 </font>

In [2]:
import numpy as np

In [5]:
R = np.matrix([ [-1,0,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,0,-1,0,-1,-1],
               [-1,0,-1,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100] ])
print(R)

[[ -1   0  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1   0  -1   0  -1  -1]
 [ -1   0  -1  -1   0  -1]
 [ -1   0   0  -1  -1 100]
 [ -1   0  -1  -1   0 100]]


In [10]:
Q= np.matrix(np.zeros([6,6]))
print(Q)

gamma = 0.8
initial_state = 1

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
def available_actions(state):
    current_state=R[state,:]
    act=np.where(current_state>=0)[1]
    return act
available_act = available_actions(initial_state)
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action
action = sample_next_action(available_act)

In [17]:
def update(current_state, action, gamma):  
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]   
    Q[current_state, action] = R[current_state, action] + gamma * max_value
update(initial_state,action,gamma)
print(Q)

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]


In [18]:
# Train over 10 000 iterations(Re-iterate the # process above)
for i in range(10000):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)
print(Q)

[[  0. 400.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0. 400.   0. 320.   0.   0.]
 [  0. 400.   0.   0. 400.   0.]
 [  0. 400. 320.   0.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]


In [25]:
print("Trained Q matrix:")
print(Q/np.max(Q)*100)

Trained Q matrix:
[[  0.  80.   0.   0.  80.   0.]
 [  0.   0.   0.  64.   0. 100.]
 [  0.  80.   0.  64.   0.   0.]
 [  0.  80.   0.   0.  80.   0.]
 [  0.  80.  64.   0.   0. 100.]
 [  0.  80.   0.   0.  80. 100.]]


In [26]:
current_state = 3
steps = [current_state]
while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index
# Print selected sequence of steps
print("Selected path:")
print(steps)

Selected path:
[3, 4, 5]
